export const menu = [
  {
    menuName: "Diamond Menu",
    starters: [
      "Cold Drink (3 flavor)",
      "Soup-2",
      "Coffee",
      "Moktails & Shake",
      "Snacks-8",
    ],
    mainCourse: [
      "Paneer-2",
      "Live Daal stall",
      "Veggies-2",
      "Rice-1 / Rice-2",
      "Rayta Bar",
      "Salad Bar",
      "Breads & Papad",
      "Sweet-3",
      "Ice cream(any flavor)",
    ],
    liveStalls: "Live Stalls-6",
  },
  {
    menuName: "Gold Menu",
    starters: [
      "Cold Drink (3 flavor)",
      "Soup-2",
      "Coffee",
      "Mojito/Shake(any flavor)",
      "Snacks-6",
    ],
    mainCourse: [
      "Paneer-2",
      "Daal-1",
      "Veggies-2",
      "Rice-1",
      "Rayta-2",
      "Salad Bar",
      "Breads & Papad",
      "Sweet-2",
      "Ice cream(any flavor)",
    ],
    liveStalls: "Live Stalls-5",
  },
  {
    menuName: "Silver Menu",
    starters: ["Cold Drink (3 flavor)", "Soup-1", "Coffee", "Snacks-4"],
    mainCourse: [
      "Paneer-1",
      "Daal-1",
      "Veggies-2",
      "Rice-1",
      "Rayta-1",
      "Salad",
      "Breads & Papad",
      "Sweet-1",
      "Ice cream(any flavor)",
    ],
    liveStalls: "Live Stalls-4",
  },
  {
    menuName: "Standard Menu (with 2 Live Stalls)",
    starters: ["Cold Drink (3 flavor)", "Soup-1", "Coffee", "Snacks-4"],
    mainCourse: [
      "Paneer-1",
      "Daal-1",
      "Veggies-2",
      "Rice-1",
      "Rayta-1",
      "Salad",
      "Breads & Papad",
      "Sweet-1",
      "Ice cream(any flavor)",
    ],
    liveStalls: "Live Stalls-2",
  },
  {
    menuName: "Basic Menu (No Soup / No Live Stalls)",
    starters: ["Cold Drink (3 flavor)", "Coffee", "Snacks-4"],
    mainCourse: [
      "Paneer-1",
      "Daal-1",
      "Veggies-1",
      "Rice-1",
      "Rayta-1",
      "Salad",
      "Breads & Papad",
      "Sweet-1",
      "Ice cream(any flavor)",
    ],
    liveStalls: "None",
  },
];
